name: Publish

on:
  push:
    tags:
      - 'T*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux.sh
            asset_name: install/linux.sh
          - os: macos-latest
            artifact_name: macos.sh
            asset_name: install/macos.sh

    steps:
    - uses: actions/checkout@v2
    - name: Run build and publish
      run: make release
    - name: Upload shell scripts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}